@echo off
echo 🔄 Starting Koshiro Fashion Server...

echo 🧹 Cleaning up existing Node.js processes...
taskkill /F /IM node.exe >nul 2>&1

echo 🔍 Waiting for processes to terminate...
timeout /t 3 /nobreak >nul

echo 🚀 Starting server...
npm run dev

pause
